// Plain-language help for every form field (shown by the ⓘ icon).
export const HELP = {
  name: { what: "What the app should call you.", example: "Priya" },
  email: { what: "The email address you sign in with.", example: "priya@gmail.com" },
  password: { what: "At least 6 characters. Only you know it.", example: "a long phrase you'll remember" },
  passwordSignin: { what: "The password you set when you created your account.", example: "the same password you signed up with" },
  urgentLabel: { what: "Name for work with near deadlines that can't wait.", example: "Applications & recruiter actions" },
  longtermLabel: { what: "Name for work that pays off later.", example: "Skills & portfolio" },
  split: { what: "Roughly how you want to split your time between urgent and long-term work.", example: "70% urgent, 30% long-term" },
  categoryTargets: { what: "Roughly how you want to split your time across categories.", example: "Career 60%, Health 10%" },
  categoryName: { what: "A part of your life you want to give time to.", example: "Health" },
  valueLabel: { what: "What you're aiming for overall. Suggestions are judged against this.", example: "career and income" },
  priorityNotes: { what: "Anything the coach should always keep in mind when suggesting.", example: "Interviews always come first. No work after 9pm." },
  coachingTone: { what: "How the coach talks to you. Direct = short and firm, Warm = encouraging, Neutral = plain.", example: "Direct" },
  replyLanguage: { what: "The language suggestions and summaries are written in.", example: "English" },
  timezone: { what: "Your local time zone, so days and deadlines line up.", example: "Asia/Kolkata" },
  projectName: { what: "A short name for the project.", example: "Product designer job hunt" },
  goal: { what: "What you want this project to achieve.", example: "Get a product designer job" },
  deadline: { what: "The date it must be done by. Leave empty if there's none.", example: "30 Nov" },
  category: { what: "Which part of your life this belongs to.", example: "Career, Health, Learning" },
  importance: { what: "How much this matters for your goals. 5 = most important.", example: "5 for your job hunt, 2 for a side hobby" },
  projectType: {
    what: "Has an end goal = finishes when a goal is reached. Has a number of parts = a set count of pieces. Habit = something you repeat.",
    example: "A job (end goal), 12 course modules (parts), exercise 3×/week (habit)",
  },
  doneDefinition: { what: "How you'll know the project is finished.", example: "Signed offer letter from a design team" },
  milestones: { what: "Big steps on the way to the goal. Weight = how much of the project each is worth.", example: "Portfolio ready (30), 20 applications sent (40)" },
  countTotal: { what: "How many parts there are in total.", example: "12 modules" },
  countDone: { what: "How many parts you've already finished.", example: "3" },
  weeklyTarget: { what: "How many sessions a week you want for this habit.", example: "3" },
  status: { what: "Active projects get suggestions. Paused or completed ones don't.", example: "Active" },
  blocker: { what: "What's stopping you right now, if anything.", example: "Waiting for feedback from mentor" },
  nextAction: { what: "The very next small step you'd take.", example: "Email Rahul about the referral" },
  progress: { what: "How far along the project is. Calculated from milestones, parts or habit sessions.", example: "40%" },
  timeAvailable: { what: "How many minutes you have right now.", example: "30" },
  energy: { what: "How much energy you have. Low gets you lighter tasks.", example: "Low after a long day" },
  outcome: { what: "How the session went overall.", example: "Made progress" },
  whereStopped: { what: "Where you left off, so it's easy to pick up next time.", example: "Halfway through the cover letter" },
  goodSuggestion: { what: "Tells the coach whether this was the right thing to work on.", example: "👍 if it fit your time and energy" },
  lessStuck: { what: "Do you feel less stuck than before? 1 = not at all, 5 = much less.", example: "4" },
  milestoneMoved: { what: "Did this session move a milestone forward?", example: "Yes" },
  resourceUsed: { what: "Did you use the saved resource during this session?", example: "Yes" },
  guard: { what: "Gentle check-ins during a session. Off = no check-ins. It never blocks anything.", example: "Check-ins every 15 min" },
  checkinInterval: { what: "How often Guard asks if you're still on task.", example: "15 minutes" },
  task: { what: "A small step you can do in one sitting.", example: "Update portfolio case study 1" },
  taskMinutes: { what: "Roughly how long the task takes.", example: "25" },
  taskEnergy: { what: "How much energy the task needs.", example: "Low for admin, High for deep work" },
  resourceUrl: { what: "The link to the video, article or page.", example: "https://youtube.com/watch?v=…" },
  resourceNote: { what: "Optional. What this helps with, in your words.", example: "Better portfolio case studies" },
  resourceTitle: { what: "A name you'll recognise later.", example: "Figma auto-layout tutorial" },
  resourceType: { what: "What kind of resource it is.", example: "Tutorial" },
  resourceProject: { what: "Which project this helps. Leave on 'Let AI pick' if unsure.", example: "Product designer job hunt" },
  topic: { what: "The subject it's about.", example: "Portfolio design" },
  problemHelped: { what: "The problem it helps you solve.", example: "Case studies feel too long" },
  summary: { what: "A short summary of the content.", example: "5 tips for tighter case studies" },
  search: { what: "Find saved resources by any word.", example: "portfolio" },
  quickNote: { what: "A quick thought to save with this session.", example: "Need better hero image" },
  roleTemplate: { what: "A starting setup for your categories and split. Picking one fills in the names for you.", example: "Job seeker" },
  sessionLengths: { what: "Session lengths you usually like, in minutes, separated by commas.", example: "25, 45, 90" },
  distractingSites: { what: "Sites that tend to pull you away, separated by commas.", example: "instagram.com, youtube.com" },
  morningBrief: { what: "A short plan for your day, sent each morning.", example: "On at 8:00" },
  briefTime: { what: "When the morning brief is sent.", example: "08:00" },
  whatsapp: { what: "Your WhatsApp number with country code, for messages from the coach.", example: "+91 98765 43210" },
  emailTag: { what: "A short tag for emails you forward to Next Action.", example: "nextaction" },
  lastAction: { what: "The last real step you finished on this project.", example: "Sent portfolio to 3 recruiters" },
  progressNotes: { what: "Anything worth remembering about how it's going.", example: "Recruiters like case study 2 most" },
  milestoneTitle: { what: "A big step on the way to the goal.", example: "Portfolio ready" },
  role: { what: "Pick the one closest to you. You can change everything after.", example: "Job seeker" },
} as const satisfies Record<string, { what: string; example?: string }>;

export type HelpKey = keyof typeof HELP;
